// src/@angular/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'fractal-app',
  template: `
    <h1>Fractal Datepicker: @angular</h1>
    <fractal-calendar-picker></fractal-calendar-picker>
    <fractal-calendar-picker [pageLength]="3"></fractal-calendar-picker>
  `
})
export class AppComponent { }

// src/react/app/app.component.tsx
import * as React from 'react'
import { CalendarPicker } from '../calendar-picker/CalendarPicker.component'

export class App extends React.Component<undefined, undefined> {
    render() {
        return (
            <div>
                <h1>Fractal Datepicker: react</h1>
                <CalendarPicker />
                <CalendarPicker pageLength={3} />
            </div>
        )
    }
}
